env:
  global:
  - secure: "QUnBlLix+kCrpi/li7BRqOdPbpSYNNyw/+8zVyY3VsnpU/j1uG+TZyk2dEMsFvkul9Zl5SnqdT8mOY+EpL5QfoG5BWyQRLRoiAHuZdkJ3bI4goNWuc6b6MpQcoW1IcPz8ZhTdDM21xR382yWNP59uqn1JQcwrY0yjyZfm27RyFyOf+3k9yNcdAwoLy4YuboQocYw80Zdsqb9OsNDXkM69y9MlPM1QcClTeNEIZRmWcsTVmTpWCeKCAoQjFH05e907SuI13fohU6YftjKutc4mvuumi6mB5SLMGLxCoRUnI+47ze65VFWweLl/el7vbmF6QG9a+Allem6TiYJkQymI/rz+C7nIQtmaayw74datN3RqJNwCA3CN8Vithv+CKhwWml/Gk726/7hufO8XMqJMGyDCwgd5zDNcaxt0CT46llaE8Bhoq9x8PD5U8ZxcDTCY/bzf4+2DgVfzk351wCFPYsCYXaktzud2VanAtlzFn+D6cXFkcMrrCxczjRMuW2xFc0kegOXLfGI5CIgonzC/CqbnMr2wbuyxAyd0RbMv5DNrl+MY8ls920tH5GRHlcencn+jqi1hy9KCAb872e9p5DcOkYFmtvHJAH4lYfM9i1V2fMTaO/o0HSJ/UUh0nKKHOXNIvOp/PmB/7z/fG+DuWFA5lRjfT6uSPoF09fpdIU="

language: php
sudo: false
matrix:
  include:
  - php: '7.2'
  - php: '7.3'
    env:
    - EXECUTE_AFTER_SCRIPT=true

cache:
  directories:
  - "$HOME/.composer/cache"
  
before_install:
- travis_retry composer self-update
- travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest

script:
- composer test:ci

after_script:
- if [[ $EXECUTE_AFTER_SCRIPT == 'true' ]]; then bash <(curl -s https://gist.githubusercontent.com/neilime/769d733c52acdecea8d2548fb3aca3ff/raw/travis_ci_php_publish_build.sh);fi
